### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by riverpaper** [Ravanger101/Cal_WinForm#1]
Hello again,

It might be a good idea to upload the source code to the repository. This way, people can see what the program does, and collaborate more effectively.

Plus, uploading source code triggers language recognition, which is one of my favourite GitHub features.

See you around!

**Comment by Ravanger101** [comment]
Yeah! I got what you want to say @TurnipGuy30. But I have made this in Visual Studio 2019, I would upload it's Files.
Regards,
Aryan

**Comment by riverpaper** [comment]
That's great! Now there's a nice little `C#` in the corner.
